general:
    # Root dir where notes are stored
    # Make sure that the target user has permission to write, read
    root_dir: 'your/notes/root/dir'

compiling:
    # Additional arguments passed to pandoc during compilation
    additional_arguments: '--number-sections'

    # Header file which is compiled at the very first
    # Useful for additional latex setup
    header_file: 'header.md'

writing:
    # Whether an external editor should be automatically opened
    open_editor: true

    # Whether an external reader should be automatically opened
    open_reader: true

    # Whether a meta file should be included in the freshly created note
    #
    # Note that even if set to false, subject name will be
    # included in the note contents
    # so pandoc can work properly (pandoc won't compile empty .md file)
    include_meta: true

    # Which editor should be used for writing if editor enabled
    editor: 'vim'

    # Which reader should be used for writing if reader enabled
    reader: 'xdg-open'

templates:
    # Custom directory used as a base structure for creating other subjects
    subject_dir: 'your/subject/dir'
    note_prefix: 'note_'

    # Where to store compiled output
    compiled_dir: 'dist'
    # Source directory for all notes
    notes_dir: 'src'

    # This file is going to be included in every note if enabled
    meta_file: 'meta.md'

    # Custom variables loaded in templates under 'config' index
    # eg. meta_file
    variables:

        author:
            name: 'Tomáš Sandrini'
            email: 'tomas.sandrini@seznam.cz'
